name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '.github/workflows/doxygen-gh-pages.yml'
      - '**.md'
      - '**.hpp'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: docs/html
          config_file: docs/doxy.conf
