name: clang-format Check
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.cpp'
      - '**.hpp'
  pull_request:
    branches: [ "main" ]
jobs:
  formatting-check:
    runs-on: ubuntu-24.04
    name: Formatting Check
    strategy:
      matrix:
        path:
          - 'lib'
          - 'client/src'
          - 'server/src'
          - 'include'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.13.0
      with:
        clang-format-version: '18'
        check-path: ${{ matrix.path }}
