name: my_cppaction

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_all:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: epitechcontent/epitest-docker:latest
      volumes:
        - ${{ github.workspace }}:/app

    steps:
    - uses: actions/checkout@v4

    - name: check compilation
      run: |
          echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
          {
            set +e
            cmake .; make
            if [ $? -ne 0 ]; then
              echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
              echo "Compilation failed."
              exit 1
            else
              echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
              exit 0
            fi
          }

#    - name: install clang-tidy
#      run: sudo dnf install -y clang-tools-extra

#    - name: install bear
#      run: sudo dnf install -y bear

    - name: code analyse
      run: |
        clang-tidy --config-file=.clang-tidy -header-filter=.* --use-color \
          `find ./client -name "*.cpp"` \
          `find ./server -name "*.cpp"` \
          `find ./lib -name "*.cpp"` \
          `find ./src -name "*.cpp"` 2>&1 | tee code_analyse_log.txt
        {
          set +e
          CLANG_TIDY_WARNING=$(grep -c "warning: " code_analyse_log.txt)
        }
        if [ "$CLANG_TIDY_WARNING" -ne 0 ]; then
          echo "::warning::$CLANG_TIDY_WARNING warning detected !"
        fi
