name: Compile & mirror

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-PAR-5-1-rtype-thibaud.cathala.git"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    uses: ./.github/workflows/compile.yml

  mirror:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [compile]
    uses: ./.github/workflows/mirror.yml
    secrets:
        SSH_KEY: ${{ secrets.SSH_KEY }}
