name: my_cppaction

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-CPP-500-PAR-5-1-rtype-thibaud.cathala.git"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_all:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    container:
      image: nicolasalexandredev/r-type:dependencies
      volumes:
        - ${{ github.workspace }}:/app

    steps:
    - uses: actions/checkout@v4

    - name: check compilation
      run: |
          echo "## 🚀 Compilation result" >> $GITHUB_STEP_SUMMARY
          {
            set +e
            cmake .; make
            if [ $? -ne 0 ]; then
              echo "- ### Compilation failed ❌" >> $GITHUB_STEP_SUMMARY
              echo "Compilation failed."
              exit 1
            else
              echo "- ### Compilation succeed ✅" >> $GITHUB_STEP_SUMMARY
              exit 0
            fi
          }

    - name: checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: code analyse
      run: |
            clang-tidy --config-file=.clang-tidy -header-filter=.* --use-color \
            `find ./client -name "*.cpp"` \
            `find ./server -name "*.cpp"` \
            `find ./lib -name "*.cpp"` \
            `find ./src -name "*.cpp"` 2>&1 | tee code_analyse_log.txt
            {
            set +e
            CLANG_TIDY_WARNING=$(grep -c "warning: " code_analyse_log.txt)
            }
            if [ "$CLANG_TIDY_WARNING" -ne 0 ]; then
            echo "::warning::$CLANG_TIDY_WARNING warning detected !"
            fi

    - name: mirror repo
      if: success()
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ env.MIRROR_URL }}
        ssh_private_key: ${{ secrets.SSH_KEY }}
